# Permalinks
permalink:           pretty

# Setup
title:               'Shashank Sharma'
tagline:             'Backend Engineer'
description:         'Just a guy who is hero for fun'
url:                 'https://shashank-sharma.xyz'
paginate:            10
baseurl:             ''
google_analytics:    'UA-160110852-1'

sass:
  sass_dir:          _sass
  style:            :compressed

# About/contact
author:
  name:              Shashank Sharma
  url:               https://shashank-sharma.xyz
  email:             shashank.sharma98@gmail.com

# Custom vars
version:             1.0.0

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-gist